# -*- coding: utf-8 -*-
"""Assignment 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n4AtmhEeasC0B7AFxA_MkdZ9IbTyBwob

## Question 1

- `Take two integer numbers and return their product. If the product is greater than 1000, then return their sum if product is less than 1000 return product value only.`
"""

# Please write The solution Here for above question 1:

def pro(a,b):
  res=a*b
  if res>1000:
    return a+b
  else:
    return res

pro(31,29) #calling the function (you can give inputs here to the function)

"""## question 2

- `Given a range of the first 10 numbers, Iterate from the start number to the end number, and In each iteration print the sum of the current number and previous number`

Expected output:
-----------------
    Printing current and previous number sum in a range(10)
    Current Number 0 Previous Number  0  Sum:  0
    Current Number 1 Previous Number  0  Sum:  1
    Current Number 2 Previous Number  1  Sum:  3
    Current Number 3 Previous Number  2  Sum:  5
    Current Number 4 Previous Number  3  Sum:  7
    Current Number 5 Previous Number  4  Sum:  9
    Current Number 6 Previous Number  5  Sum:  11
    Current Number 7 Previous Number  6  Sum:  13
    Current Number 8 Previous Number  7  Sum:  15
    Current Number 9 Previous Number  8  Sum:  17
"""

# Please write The solution Here for above question 2:
def num():
  prev_num=0
  print("printing Current and previous number sum in a range(10)")
  for i in range(0,10):
    sum=prev_num+i
    print(f'Current Number',i,'Previous Number',prev_num,'Sum:',sum)
    prev_num=i
num()

"""## question 3

Given a string and an integer number n, remove characters from a string starting from zero up to n and return a new string

- Example :
     `("pynative", 4) so output must be tive.`
     
     `Note: n must be less than the length of the string.`
"""

# Please write The solution Here for above question 3:

def rem(a,n):
  if n > len(a):
    return False
  else:
    return a[n:]

a="pynative" #input string value
n=4   # given a integer n value
rem(a,n)

"""## question 4

### `Given a list of numbers, return True if first and last number of a list is same`

    Expected Output:
    -------------------------------------

    Given list is
    a =  [10, 20, 30, 40, 10]
    b = [10 , 20 , 30 , 40, 10 ]
    result is True

    Given list is  
    a = [10, 20, 30, 40, 50]
    b = [11 , 21 , 31 , 41 , 51 ]
    result is False
"""

# Please write The solution Here for above question 4:

def fir_last_same(a):
  first=a[0]
  last=a[-1]
  if first==last:
    return True
  else:
    return False

a1=[10,20,30,40,10]# input list
a2=[11,21,31,41,11]
fir_last_same(a1)#calling function
fir_last_same(a2)

print(f"Given list is \n a={a1}\n b={a2}\n result is {fir_last_same(a1)}")

a1=[10,20,30,40,50]# input list
a2=[11,21,31,41,51]
fir_last_same(a1)#calling function
fir_last_same(a2)

print(f"\n\nGiven list is \n a={a1}\n b={a2}\n result is {fir_last_same(a1)}")

"""## question 5

### Given a two Python list. Iterate both lists simultaneously such that list1 should display item in original order and list2 in reverse order

    list1 = [10, 20, 30, 40]
    list2 = [100, 200, 300, 400]


    Expected output:
    -----------------------------
    10 400
    20 300
    30 200
    40 100
"""

# Please write The solution Here for above question 5:
list1=[10,20,30,40]
list2=[100,200,300,400]

for i in range(len(list1)):
  print(f'{list1[i]},{list2[-(i+1)]}')

"""## question 6

### Remove empty strings from the list of strings


    list1 = ["Mike", "", "Emma", "Kelly", "", "Brad"]

    Expected output:
    ----------------------

    ["Mike", "Emma", "Kelly", "Brad"]
"""

# Please write The solution Here for above question 6:
def empty(list1):
  emp=[]
  for i in list1:
    if i=='':
      continue
    else:
      emp.append(i)
  print(emp)

list1=["Mike", "", "Emma", "Kelly", "", "Brad"]
empty(list1)













