# -*- coding: utf-8 -*-
"""Python_Strings .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ZCb8PtG1-Hi-Wr5sORV5R7mHQHFcbqc

<a href="https://www.viharatech.com"><img src="https://miro.medium.com/v2/resize:fit:828/format:webp/1*on2Bpj6A5gfd-CzaFOAZRA.jpeg"></a>


- `Welcome to our interactive learning session! In this Jupyter notebook, you'll find a series of questions related to Python String Concept. To maximize your learning, please write Python code in the cell below each question and execute it. This hands-on practice will help reinforce your understanding of the concepts. Feel free to reach out if you have any questions or need assistance. Happy coding! 💻🐍 `

### Question 1: Write a Python program to count the number of characters in a string without using len function.

- `sample input : `
    - `var = 'python java'`
- `sample output :`
    - `result : 11`
"""

# Please write The solution Here for above question 1:
a='python java'
res=0
for i in a:
  res=res+1

print(res)

"""### Question 2: Write a Python program to reverse a string without using [::-1]

- `sample input : `
    - `var = 'python'`
- `sample output :`
    - `result : nohtyp`
"""

# Please write The solution Here for above question 2:
var = 'python'
rev =''

for i in var:
  rev = i + rev

print(rev)

"""### Question 3: Write a Python program to check if a string is a palindrome don't use [::-1].

- `sample input : `
    - `var = 'NUN'`
- `sample output :`
    - `result : It is a Palindrome`
    
- `palindrome concept = https://www.dictionary.com/e/palindromic-word/#:~:text=A%20palindrome%20is%20a%20word,roots%20in%20the%20early%201600s.`
"""

# Please write The solution Here for above question 3:
var='NUN'
temp=var
res=''

for i in var:
  res=i+res

if(temp==res):
  print('It is palindrome')

else:
  print('It is not a palindrome')

"""### Question 4: Write a Python program to find the most common character in a string.

- `sample input : `
    - `var = 'Hello world '`
- `sample output :`
    - `result : l, because l is repeating 3 times `
"""

# Please write The solution Here for above question 4:

var='Hello world'
res=''
freq=0

for i in var:
  count=var.count(i)
  if(count>freq):
    freq=count
    res=i
print(res,',because',res,'is repeating 3 times')

"""### Question 5: Write a Python program to check if two strings are anagrams.

- `sample input : `
    - `var1 = 'listen'`
    - `var2 = 'silent'`
- `sample output :`
    - `result : both are anagram because characters in var1 should present in var2 `
"""

# Please write The solution Here for above question 5:
var1='listen'
var2='silent'

res1=sorted(var1)
res2=sorted(var2)

if(res1==res2):
  print("both are anagram because characters in var1 should present in var2")

else:
  print("not an anagram")

"""### Question 6: Write a Python program to remove all the vowels from a string.

- `sample input : `
    - `var = 'python'`
- `sample output :`
    - `result : pythn , because vowels are [AEIOUaeiou]`
"""

# Please write The solution Here for above question 6:
var='python'
res=''
vowels='AEIOUaeiou'

for i in var:
  if i in vowels:
    next
  else:
    res = res+ i
print(res,', because vowels are', vowels)

"""### Question 7: Write a Python program to find the longest word in a string.

- `sample input : `
    - `var = 'python is Easy Language'`
- `sample output :`
    - `result : Language`
"""

# Please write The solution Here for above question 7:
def long(sent):
  word=sent.split()
  long_word=''
  max_length=0

  for i in word:
    if len(i)>max_length:
      long_word=i
      max_length=len(i)
  return long_word
sent="pyhton is a language"
long(sent)

"""### Question 8: Write a Python program to capitalize the first letter of each word in a string [dont use built-in-function title].

- `sample input : `
    - `var = 'python is easy'`
- `sample output :`
    - `result : Python Is Easy`
"""

# Please write The solution Here for above question 8:

def cap(var):
  res=''
  for i in var.split():
    res=res+i[0].upper()+i[1:]+" "
  return res

var='python is easy'
cap(var)

"""### Question 9: Write a Python program to find the frequency of each character in a string.

- `sample input : `
    - `var = 'sharuk khan'`
- `sample output :`
    - `result : {'s': 1, 'h': 2, 'a': 2, 'r': 1, 'u': 1, 'k': 2, ' ': 1, 'n': 1}`
"""

# Please write The solution Here for above question 9:
var='sharuk khan'
res={}

for i in var:
  if i in res:
    res[i] += 1
  else:
    res[i]=1
print(res)

"""### Question 10: write a python programme to find the sum of all the even characters based on Ascii values

- `sample input : `
    - `var = 'sharuk khan'`
- `sample output :`
    - `result : 464`

"""

# Please write The solution Here for above question 10:
var='sharuk khan'
sum=0

for i in var:
  if(ord(i)%2==0):
    sum+=ord(i)
print(sum)

