# -*- coding: utf-8 -*-
"""Python_List assigment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aj_oqy6SggPDp6A1V7fML6VTmSY9L2om

<a href="https://www.viharatech.com"><img src="https://miro.medium.com/v2/resize:fit:828/format:webp/1*on2Bpj6A5gfd-CzaFOAZRA.jpeg"></a>


- `Welcome to our interactive learning session! In this Jupyter notebook, you'll find a series of questions related to Python List Concept. To maximize your learning, please write Python code in the cell below each question and execute it. This hands-on practice will help reinforce your understanding of the concepts. Feel free to reach out if you have any questions or need assistance. Happy coding! 💻🐍 `

### Question 1: Write a Python program to count the number of elements in a list without using len.


- `sample input : `
    - `var = [10,11,12,13]`
- `sample output :`
    - `result : 4`
"""

# Please write The solution Here for above question 1:

def num(var):
  result=0
  for i in var:
    result+=1
  return result

var=[10,11,12,13]
num(var)

"""### Question 2: Write a Python program to find the maximum and minimum values in a given list.

- `sample input : `
    - `var = [10,11,12,13,14,15]`
- `sample output :`
    - `result : max = 15 , min = 10`
"""

# Please write The solution Here for above question 2:
def find_max_min(input_list):
    max_value = input_list[0]
    min_value = input_list[0]
    for item in input_list:
        if item > max_value:
            max_value = item
        if item < min_value:
            min_value = item

    return max_value, min_value

var = [10, 11, 12, 13, 14, 15]
max_value, min_value = find_max_min(var)
print(f"result: max = {max_value}, min = {min_value}")

"""### Question 3: Write a Python program to remove the first occurrence of a specified element from a list.

- `sample input : `
    - `var = [1,2,3,4,2,5]`
- `sample output :`
    - `result : [1,3,4,2,5]`
    
"""

def rmf(list,ele):
  if ele in list:
    list.remove(ele)
  return list
var=[1,2,3,4,2,5]
ele_remove=2

res=rmf(var,ele_remove)

print("result :",res)

"""### Question 4: Write a Python program to find the average of all the elements in a list.


- `sample input : `
    - `var = [1,2,3,4,2,5]`
- `sample output :`
    - `result : 2.833 `
"""

# Please write The solution Here for above question 4:
def avg(var):
  ele=num(var)
  sum=0
  for i in var:
    sum+=i
  print(f'sum:',sum)
  print(f'ele:',ele)
  print(f'average',sum/ele)
var=[1,2,3,4,2,5]
avg(var)

"""### Question 5: Write a Python program to check if a list is empty or not.


- `sample input : `
    - `var1 = [1,2]`
- `sample output :`
    - `result : Not empty`
    
- `sample input : `
    - `var1 = []`
- `sample output :`
    - `result :empty`
    

"""

# Please write The solution Here for above question 5:
def empty(var):
  if num(var)==0:
    print("Empty")
  else:
    print("Not empty")

var=[1,2,3]
empty(var)
var=[]
empty(var)

"""### Question 6:  Write a Python program to find the index of a specified element in a list..

- `sample input : `
    - `var = [1,2,3,4,2,5]`
- `sample output :`
    - `result : 3 index is 2`
"""

def index(var,ele):
  for i in range(len(var)):
    if var[i]==ele:
      return i
  return -1

var=[1,2,3,4,2,5]
ele_to_find=2
res=index(var,ele_to_find)

if res != -1:
  print(f"result: {ele_to_find} index is {res}")
else:
  print(f"result: {ele_to_find} not found in list")

"""### Question 7: Write a Python program to find which number is palindrome in below given list .

- `sample input : `
    - `var = [134,121,155]`
- `sample output :`
    - `result : 134 is not a palindome , 121 is a palindrome `
"""

def palindrome(ele):
    return str(ele) == str(ele)[::-1]

def is_palindrome(var):
    results = []
    for ele in var:
        if palindrome(ele):
            results.append(f"{ele} is a palindrome")
        else:
            results.append(f"{ele} is not a palindrome")
    return ", ".join(results)

var = [134, 121, 151]
result = is_palindrome(var)

print("result:", result)

"""### Question 8: Write a Python program to find the common elements between two lists.

- `sample input : `
    - `var1 = [1,2,3,4,10]`
    - `var2 = [10,11,12,14]`
- `sample output :`
    - `result : 10`

    
"""

# Please write The solution Here for above question 8:
def common(var1,var2):
  var1=set(var1)
  var2=set(var2)
  common_ele=var1.intersection(var2)
  return list(common_ele)

var1=[1,2,3,4,10]
var2=[10,11,12,14]

res=common(var1,var2)
print(f"result :", (res))

"""### Question 9: Write a Python program to remove the duplicates from a list

- `sample input : `
    - `var = [10,11,12,10,12,24]`
- `sample output :`
    - `result : [10,11,12,24]`
"""

# Please write The solution Here for above question 9:

def rem(var):
  res=[]
  for i in var:
    if i not in res:
      res.append(i)
    return res

var=[10,11,12,10,12,24]
rem(var)

"""### Question 10:  Write a Python program to sort a list of strings in Ascii Order [Ascending order]


- `sample input : `
    - `var = ['a' , 'c' , 'b']`
- `sample output :`
    - `result : ['a' , 'b' , 'c']`

"""

# Please write The solution Here for above question 10:
def sort(var):
  return sorted(var, key=lambda x:ord(x))

var=['a','c','b']
sort(var)





